# Generated by Django 5.2.5 on 2025-08-14 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('game', '0003_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('team', 'Team'), ('private', 'Private')], max_length=30),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='game.team'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('team',), name='unique_team_chat'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('user_1', 'user_2'), name='unique_private_chat'),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
    ]
