# Generated by Django 5.2.5 on 2025-08-07 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Game Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_time', models.DateTimeField(help_text='Date and time when the game starts', verbose_name='Start Time')),
                ('is_active', models.BooleanField(default=False)),
                ('game_type', models.CharField(choices=[('solo', 'Solo Player'), ('team', 'Team Based'), ('both', 'Both Solo and Team')], default='solo', help_text='Specify if the game is for solo player, teams or both.', max_length=10)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
