# Generated by Django 5.2.5 on 2025-08-12 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('join_code', models.CharField(editable=False, max_length=8, unique=True)),
                ('max_member', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['start_time'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['start_time'], name='game_game_start_t_599070_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_active'], name='game_game_is_acti_ad9601_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['game_type'], name='game_game_game_ty_7cd476_idx'),
        ),
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='game.game'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'game')},
        ),
    ]
